# Generated by Django 2.0.3 on 2018-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0002_auto_20180424_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
