# Generated by Django 2.0.3 on 2018-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0003_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='national_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
