# Generated by Django 2.0.3 on 2018-04-23 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0004_users_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
