# Generated by Django 2.0.3 on 2018-05-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0008_services_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
