# Generated by Django 2.0.3 on 2018-05-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0010_business_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='history',
        ),
    ]
