# Generated by Django 2.0.3 on 2018-05-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0011_remove_users_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='pics',
        ),
        migrations.RemoveField(
            model_name='services',
            name='pics',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.AddField(
            model_name='sans',
            name='time_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Zanbil.TimeTable'),
        ),
    ]
