# Generated by Django 2.0.3 on 2018-05-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0012_auto_20180526_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('Business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_id', to='Zanbil.Business')),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_id', to='Zanbil.Services')),
            ],
        ),
    ]
