# Generated by Django 2.0.3 on 2018-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0013_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
