# Generated by Django 2.0.3 on 2018-05-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0014_pics_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserves',
            name='sans_no',
        ),
        migrations.AddField(
            model_name='reserves',
            name='sans_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Zanbil.Sans'),
        ),
    ]
