# Generated by Django 2.0.3 on 2018-05-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0015_auto_20180527_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='reserves',
            old_name='sans_id',
            new_name='sans',
        ),
        migrations.RenameField(
            model_name='reserves',
            old_name='timetable_id',
            new_name='timetable',
        ),
        migrations.RenameField(
            model_name='reserves',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
