# Generated by Django 2.0.3 on 2018-05-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0016_auto_20180527_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='Business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='Zanbil.Business'),
        ),
        migrations.AlterField(
            model_name='pics',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='Zanbil.Services'),
        ),
    ]
