# Generated by Django 2.0.3 on 2018-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0017_auto_20180527_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
