# Generated by Django 2.0.3 on 2018-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0018_auto_20180527_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves',
            name='date',
            field=models.CharField(max_length=150),
        ),
    ]
