# Generated by Django 2.0.3 on 2018-05-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0019_auto_20180527_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserves',
            name='timetable',
        ),
        migrations.AddField(
            model_name='timetable',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Zanbil.Business'),
        ),
    ]
