# Generated by Django 2.0.3 on 2018-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0021_auto_20180528_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='sans',
            name='weekday',
            field=models.PositiveIntegerField(default=111),
            preserve_default=False,
        ),
    ]
