# Generated by Django 2.0.3 on 2018-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0022_sans_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sans',
            name='weekday',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
