# Generated by Django 2.0.3 on 2018-06-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0022_sans_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.AddField(
            model_name='review',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='Zanbil.Business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Zanbil.Categories'),
        ),
        migrations.AlterField(
            model_name='business',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
