# Generated by Django 2.0.3 on 2018-07-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0023_auto_20180609_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='2.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='services',
            name='firstSans',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='services',
            name='lastSans',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='services',
            name='restTimeEnd',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='services',
            name='restTimeStart',
            field=models.FloatField(default=12),
        ),
        migrations.AlterField(
            model_name='services',
            name='cancelation_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='cancellation_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='off',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
