# Generated by Django 2.0.7 on 2018-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zanbil', '0024_auto_20180708_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sans',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sans',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
